#ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  dbname: EPAM_LABS
#Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  username: cGV0Y2xpbmlj
  password: cGV0Y2xpbmlj
  rootpassword: am9qbw==
#Service
---
apiVersion: v1
kind: Service
metadata:
  name: db-host
  labels:
    app: pet-svc
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
#Persistant volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/data"
# Persistant volume cliam
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
#StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ss
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: dbname
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: rootpassword   
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data  
        persistentVolumeClaim:
          claimName: mysql-pv-claim
