apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 17062000/k8s-pet
        ports:
        - containerPort: 8080

