#ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pet-profile
data:
  profile: mysql
  application-mysql-properties: |
    database=mysql
    spring.datasource.url=jdbc:mysql://db-host/EPAM_LABS
    spring.datasource.username=petclinic
    spring.datasource.password=petclinic
    spring.datasource.initialization-mode=always

#Service
---
apiVersion: v1
kind: Service
metadata:
  name: pet-service
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
  type: LoadBalancer
#Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-dpl
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: petclinic
        image: 17062000/k8s-pet
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: pet-profile
              key: profile
        ports:
        - containerPort: 8080
        volumeMounts:
            - mountPath: "/home/petclinic-app/config"
              name: petclinic-application-properties
      volumes:
        - name: petclinic-application-properties
          configMap:
            name: pet-profile
            items:
            - key: application-mysql-properties
              path: application-mysql.properties
